# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b1964081c9ea38a0b280f5c0ce9442ca0241e1a48ba75ab845f3cd8964a55a2b8b1120567024d28021a3993887b04e30cf6288bee5fe2a58de266bfed8cdc4bd

test:
  secret_key_base: 75e23b7d6727188793675026d3aa443c0246df6adf267fa0766dda7dd8fb404242f4fd8c3e857bdfda8b337c5f6880d53e17f71311f5e043ca834ed34fbd62b1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
